---
abstract: 'make slides easy'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Pod-Slide
provides:
  Perl6::Pod::Slide:
    file: lib/Perl6/Pod/Slide.pm
    version: 0.02
requires:
  Perl6::Pod: 0.26_12
  Test::Class: 0
  XML::ExtOn: 0.14
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Perl6::Pod::Slide
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zag/p5-Perl6-Pod-Slide.git
version: 0.02
